"""schema inicial

Revision ID: 02fff720a26e
Revises: 
Create Date: 2026-09-12 12:49:00.373860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02fff720a26e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alunos_email'), 'alunos', ['email'], unique=True)
    op.create_table('professores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('senha_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_professores_email'), 'professores', ['email'], unique=True)
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_turma', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turmas_codigo_turma'), 'turmas', ['codigo_turma'], unique=True)
    op.create_index(op.f('ix_turmas_professor_id'), 'turmas', ['professor_id'], unique=False)
    op.create_table('aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_aula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modo_atual', sa.Enum('livre', 'foco', 'atividade', name='modoaula'), nullable=False),
    sa.Column('status', sa.Enum('nao_iniciada', 'em_andamento', 'encerrada', name='statusaula'), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(), nullable=True),
    sa.Column('encerrada_em', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aulas_codigo_aula'), 'aulas', ['codigo_aula'], unique=True)
    op.create_index(op.f('ix_aulas_turma_id'), 'aulas', ['turma_id'], unique=False)
    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('matriculado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_matriculas_aluno_id'), 'matriculas', ['aluno_id'], unique=False)
    op.create_index(op.f('ix_matriculas_turma_id'), 'matriculas', ['turma_id'], unique=False)
    op.create_table('participacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.Column('entrou_em', sa.DateTime(), nullable=False),
    sa.Column('score_foco_segundos', sa.Integer(), nullable=False),
    sa.Column('score_aprendizagem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participacoes_aluno_id'), 'participacoes', ['aluno_id'], unique=False)
    op.create_index(op.f('ix_participacoes_aula_id'), 'participacoes', ['aula_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modo_execucao', sa.Enum('individual', 'grupo', name='modoexecucaoquiz'), nullable=False),
    sa.Column('competitivo', sa.Boolean(), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('meta_coletiva_percentual', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_aula_id'), 'quizzes', ['aula_id'], unique=False)
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('nome_ou_numero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_quiz_id'), 'grupos', ['quiz_id'], unique=False)
    op.create_table('perguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sa.Enum('multipla_escolha', 'verdadeiro_falso', 'aberta', name='tipopergunta'), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perguntas_quiz_id'), 'perguntas', ['quiz_id'], unique=False)
    op.create_table('alternativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('texto', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correta', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alternativas_pergunta_id'), 'alternativas', ['pergunta_id'], unique=False)
    op.create_table('grupo_membros',
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('participacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['participacao_id'], ['participacoes.id'], ),
    sa.PrimaryKeyConstraint('grupo_id', 'participacao_id')
    )
    op.create_table('respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('participacao_id', sa.Integer(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('alternativa_id', sa.Integer(), nullable=True),
    sa.Column('resposta_texto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('correta', sa.Boolean(), nullable=True),
    sa.Column('respondido_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alternativa_id'], ['alternativas.id'], ),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.ForeignKeyConstraint(['participacao_id'], ['participacoes.id'], ),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_respostas_grupo_id'), 'respostas', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_respostas_participacao_id'), 'respostas', ['participacao_id'], unique=False)
    op.create_index(op.f('ix_respostas_pergunta_id'), 'respostas', ['pergunta_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_respostas_pergunta_id'), table_name='respostas')
    op.drop_index(op.f('ix_respostas_participacao_id'), table_name='respostas')
    op.drop_index(op.f('ix_respostas_grupo_id'), table_name='respostas')
    op.drop_table('respostas')
    op.drop_table('grupo_membros')
    op.drop_index(op.f('ix_alternativas_pergunta_id'), table_name='alternativas')
    op.drop_table('alternativas')
    op.drop_index(op.f('ix_perguntas_quiz_id'), table_name='perguntas')
    op.drop_table('perguntas')
    op.drop_index(op.f('ix_grupos_quiz_id'), table_name='grupos')
    op.drop_table('grupos')
    op.drop_index(op.f('ix_quizzes_aula_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index(op.f('ix_participacoes_aula_id'), table_name='participacoes')
    op.drop_index(op.f('ix_participacoes_aluno_id'), table_name='participacoes')
    op.drop_table('participacoes')
    op.drop_index(op.f('ix_matriculas_turma_id'), table_name='matriculas')
    op.drop_index(op.f('ix_matriculas_aluno_id'), table_name='matriculas')
    op.drop_table('matriculas')
    op.drop_index(op.f('ix_aulas_turma_id'), table_name='aulas')
    op.drop_index(op.f('ix_aulas_codigo_aula'), table_name='aulas')
    op.drop_table('aulas')
    op.drop_index(op.f('ix_turmas_professor_id'), table_name='turmas')
    op.drop_index(op.f('ix_turmas_codigo_turma'), table_name='turmas')
    op.drop_table('turmas')
    op.drop_index(op.f('ix_professores_email'), table_name='professores')
    op.drop_table('professores')
    op.drop_index(op.f('ix_alunos_email'), table_name='alunos')
    op.drop_table('alunos')
    # ### end Alembic commands ###
